version: "3"
services:
  mysqldb:
    image: mysql
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  application:
    image: spring-boot-mysql-app
    ports:
      - "9090:9090"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/Anargya?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root      
networks:
  springboot-db-net: